name: Build OnePlus 6 and 6t KernelSU Kernel
on:
  workflow_dispatch:
  push:
    branches:
      - HEAD
  pull_request:
      branches:
      - HEAD

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CCACHE_COMPILERCHECK: "%compiler% -dumpmachine; %compiler% -dumpversion"
      CCACHE_NOHASHDIR: "true"
      CCACHE_MAXSIZE: "2G"
      CCACHE_HARDLINK: "true"
      KERNEL_DEFCONFIG: "shapeless_defconfig"
      KERNEL_CMDLINE: "O=out clean mrproper"
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 100

    - name: Set up ccache
      uses: hendrikmuhs/ccache-action@v1.2

    - name: Install dependencies
      run: |
        sudo apt-get update -y 
        sudo apt-get install autoconf
        sudo apt install gcc-aarch64-linux-gnu -y
        sudo apt install gcc-arm-linux-gnueabi -y
        sudo apt install binutils make python3 libssl-dev build-essential bc  bison flex unzip libssl-dev ca-certificates xz-utils mkbootimg cpio device-tree-compiler git git-lfs -y
        mkdir toolchain
        cd toolchain
        git clone --depth=1 https://github.com/pkm774/android-kernel-tools tools
        cd ..
        git clone https://github.com/Coconutat/AnyKernel3_Backup -b Op6_KSU --depth=1
        rm -rf AnyKernel3/.git
    
    - name: GetTime
      id: get_time
      run: |
        echo "TIME=$(TZ=UTC+5:30 date +%m%d%H%M )" >> $GITHUB_OUTPUT
    - name: Build Kernel-With-KernelSU
      run: |
        make distclean
        rm -rf KernelSU
        rm -rf drivers/kernelsu
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
        PATH="$TOP/toolchain/tools/sdclang/linux-x86_64/bin:$PATH"
        export ARCH=arm64
        export SUBARCH=ARM64
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi
        make $KERNEL_CMDLINE $KERNEL_DEFCONFIG CC="ccache clang"
        make o=out CC="ccache clang" -j$(nproc --all)
        cp out/arch/arm64/boot/Image.gz-dtb AnyKernel3_Backup
    - name: Upload Kernel-SU
      uses: actions/upload-artifact@v3
      with:
        name: caffeineQ_kernel_op6-KSU-${{ steps.get_time.outputs.TIME }}
        path: "AnyKernel3_Backup/*"
